# Generated by Django 4.1 on 2022-12-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Integrante',
        ),
    ]
